import { Injectable } from '@angular/core';
import { StoryImage } from '../models/story-image.model';

@Injectable({
  providedIn: 'root',
})
export class StoryDataService {
  private data: StoryImage[] = [
    {
      //0.Scene 1
      backgroundSrc: 'start.png',
      elements: [
        {
          classes: 'animation top-to-bottom',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_1_e2.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '4.44%',
          width: '19.22%',
          xPos: '33.7%',
          yPos: '8.15%',
        },
        {
          classes: 'animation bottom-to-top',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_1_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '8.24%',
          width: '63.39%',
          xPos: '17.6%',
          yPos: '82.04%',
        },
      ],
      nextFrame: 1,
      prevFrame: 0,
      shouldTransition: false,
    },
    {
      //1.Scene 2
      backgroundSrc: 'start.png',
      elements: [
        {
          classes: '',
          isNextButton: false,
          isStoryLink: false,
          src: 'scene_1_e2.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '4.44%',
          width: '19.22%',
          xPos: '33.7%',
          yPos: '8.15%',
        },
        {
          classes: 'animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_2_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '8.06%',
          width: '10.0%',
          xPos: '45.0%',
          yPos: '82.13%',
        },
      ],
      nextFrame: 2,
      prevFrame: 0,
      shouldTransition: true,
    },
    {
      //2.Scene 3
      backgroundSrc: 'sky_trees.gif',
      elements: [
        {
          classes: 'first animation right-to-left',
          isNextButton: false,
          isStoryLink: false,
          src: 'scene_3_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '100%',
          width: '100%',
          xPos: '0',
          yPos: '0',
        },
        {
          classes: 'second animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_3_e2.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '20.09%',
          width: '47.08%',
          xPos: '26.46%',
          yPos: '7.78%',
        },
      ],
      nextFrame: 3,
      prevFrame: 1,
      shouldTransition: false,
    },
    {
      //3.Scene 4
      backgroundSrc: 'sky_trees.gif',
      elements: [
        {
          classes: 'first',
          isNextButton: false,
          isStoryLink: false,
          src: 'scene_3_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '100%',
          width: '100%',
          xPos: '0',
          yPos: '0',
        },
        {
          classes: 'second animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_4_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '24.07%',
          width: '48.54%',
          xPos: '22.6%',
          yPos: '17.87%',
        },
      ],
      nextFrame: 4,
      prevFrame: 2,
      shouldTransition: false,
    },
    {
      //4.Scene 5
      backgroundSrc: 'sky_trees.gif',
      elements: [
        {
          classes: 'first',
          isNextButton: false,
          isStoryLink: false,
          src: 'scene_5_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '100%',
          width: '100%',
          xPos: '0',
          yPos: '0',
        },
        {
          classes: 'second animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_5_e2.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '24.07%',
          width: '48.54%',
          xPos: '22.6%',
          yPos: '17.87%',
        },
      ],
      nextFrame: 5,
      prevFrame: 3,
      shouldTransition: true,
    },
    {
      //5.Scene 6
      backgroundSrc: 'corridoor.gif',
      elements: [
        {
          classes: 'animation fade-in',
          isNextButton: false,
          isStoryLink: false,
          src: 'scene_6_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '5.65%',
          width: '15.99%',
          xPos: '2.86%',
          yPos: '5.09%',
        },
        {
          classes: 'animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_6_e2.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '11.57%',
          width: '19.79%',
          xPos: '35.73%',
          yPos: '25.65%',
        },
      ],
      nextFrame: 6,
      prevFrame: 4,
      shouldTransition: false,
    },
    {
      //6.Scene 7
      backgroundSrc: 'corridoor.gif',
      elements: [
        {
          classes: 'animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_7_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '14.81%',
          width: '22.24%',
          xPos: '44.9%',
          yPos: '24.81%',
        },
      ],
      nextFrame: 7,
      prevFrame: 5,
      shouldTransition: false,
    },
    {
      //7.Scene 8
      backgroundSrc: 'corridoor.gif',
      elements: [
        {
          classes: 'animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_5_e2.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '8.98%',
          width: '16.51%',
          xPos: '37.5%',
          yPos: '28.33%',
        },
      ],
      nextFrame: 8,
      prevFrame: 6,
      shouldTransition: true,
    },
    {
      //8.Scene 9
      backgroundSrc: 'scene_8.png',
      elements: [
        {
          classes: 'first',
          isNextButton: false,
          isStoryLink: false,
          src: 'vapours.gif',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '100%',
          width: '100%',
          xPos: '0',
          yPos: '0',
        },
        {
          classes: 'second animation fade-in',
          isNextButton: false,
          isStoryLink: false,
          src: 'scene_8_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '5.65%',
          width: '15.89%',
          xPos: '1.77%',
          yPos: '2.96%',
        },
        {
          classes: 'third animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_8_e2.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '17.5%',
          width: '29.74%',
          xPos: '9.95%',
          yPos: '11.02%',
        },
      ],
      nextFrame: 9,
      prevFrame: 7,
      shouldTransition: false,
    },
    {
      //9.Scene 10
      backgroundSrc: 'scene_8.png',
      elements: [
        {
          classes: 'first',
          isNextButton: false,
          isStoryLink: false,
          src: 'vapours.gif',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '100%',
          width: '100%',
          xPos: '0',
          yPos: '0',
        },
        {
          classes: 'second animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_9_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '22.41%',
          width: '33.7%',
          xPos: '5.62%',
          yPos: '2.96%',
        },
      ],
      nextFrame: 10,
      prevFrame: 8,
      shouldTransition: true,
      nextGameIs: 'curry',
    },
    {
      //10.Scene 11
      backgroundSrc: 'scene_10.png',
      elements: [
        {
          classes: 'first',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_10_e7.gif',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '6.3%',
          width: '8.85%',
          xPos: '88.07%',
          yPos: '91.57%',
        },
        {
          classes: 'first',
          isNextButton: false,
          isStoryLink: true,
          src: 'scene_10_e2.png',
          storyLinkedFrame: 11,
          storyLinkViewed: false,
          styles: '',
          height: '27.5%',
          width: '22.19%',
          xPos: '21.04%',
          yPos: '56.3%',
        },
        {
          classes: 'first',
          isNextButton: false,
          isStoryLink: true,
          src: 'scene_10_e4.png',
          storyLinkedFrame: 12,
          storyLinkViewed: false,
          styles: '',
          height: '18.7%',
          width: '10.89%',
          xPos: '68.39%',
          yPos: '41.94%',
        },
        {
          classes: 'first',
          isNextButton: false,
          isStoryLink: true,
          src: 'scene_10_e1.png',
          storyLinkedFrame: 13,
          storyLinkViewed: false,
          styles: '',
          height: '25.83%',
          width: '18.8%',
          xPos: '19.64%',
          yPos: '8.52%',
        },
        {
          classes: 'first',
          isNextButton: false,
          isStoryLink: true,
          src: 'scene_10_e5.png',
          storyLinkedFrame: 14,
          storyLinkViewed: false,
          styles: '',
          height: '26.85%',
          width: '16.04%',
          xPos: '67.14%',
          yPos: '11.57%',
        },
        {
          classes: 'first',
          isNextButton: false,
          isStoryLink: true,
          src: 'scene_10_e3.png',
          storyLinkedFrame: 15,
          storyLinkViewed: false,
          styles: '',
          height: '38.98%',
          width: '31.87%',
          xPos: '35.52%',
          yPos: '24.72%',
        },
        {
          classes: 'first',
          isNextButton: false,
          isStoryLink: true,
          src: 'scene_10_e6.png',
          storyLinkedFrame: 21,
          storyLinkViewed: false,
          styles: '',
          height: '21.94%',
          width: '11.56%',
          xPos: '15.83%',
          yPos: '33.8%',
        },
      ],
      nextFrame: 25,
      prevFrame: 9,
      shouldTransition: false,
    },
    {
      //11.Scene 12
      backgroundSrc: 'dining_table.gif',
      elements: [
        {
          classes: 'first',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_11_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '39.35%',
          width: '49.79%',
          xPos: '35.36%',
          yPos: '27.41%',
        },
      ],
      nextFrame: 10,
      prevFrame: 10,
      shouldTransition: false,
    },
    {
      //12.Scene 13
      backgroundSrc: 'dining_table.gif',
      elements: [
        {
          classes: 'first',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_12_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '36.67%',
          width: '42.34%',
          xPos: '31.72%',
          yPos: '13.33%',
        },
      ],
      nextFrame: 10,
      prevFrame: 10,
      shouldTransition: false,
    },
    {
      //13.Scene 14
      backgroundSrc: 'dining_table.gif',
      elements: [
        {
          classes: 'first',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_13_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '29.17%',
          width: '42.81%',
          xPos: '30.0%',
          yPos: '19.54%',
        },
      ],
      nextFrame: 10,
      prevFrame: 10,
      shouldTransition: false,
    },
    {
      //14.Scene 15
      backgroundSrc: 'dining_table.gif',
      elements: [
        {
          classes: 'first',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_14_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '33.8%',
          width: '49.79%',
          xPos: '25.1%',
          yPos: '22.5%',
        },
      ],
      nextFrame: 10,
      prevFrame: 10,
      shouldTransition: false,
    },
    {
      //15.Scene 16
      backgroundSrc: 'scene_15.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_15_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '19.63%',
          width: '30.16%',
          xPos: '26.15%',
          yPos: '50.0%',
        },
      ],
      nextFrame: 16,
      prevFrame: 10,
      shouldTransition: false,
    },
    {
      //16.Scene 17
      backgroundSrc: 'scene_15.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_16_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '15.83%',
          width: '33.8%',
          xPos: '28.44%',
          yPos: '55.56%',
        },
      ],
      nextFrame: 17,
      prevFrame: 15,
      shouldTransition: false,
    },
    {
      //17.Scene 18
      backgroundSrc: 'scene_15.png',
      elements: [
        {
          classes: 'first',
          isNextButton: false,
          isStoryLink: false,
          src: 'scene_17_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '39.63%',
          width: '28.91%',
          xPos: '4.22%',
          yPos: '10.37%',
        },
        {
          classes: 'second animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_17_e2.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '18.43%',
          width: '33.54%',
          xPos: '26.77%',
          yPos: '51.67%',
        },
      ],
      nextFrame: 18,
      prevFrame: 16,
      shouldTransition: false,
    },
    {
      //18.Scene 19
      backgroundSrc: 'scene_15.png',
      elements: [
        {
          classes: 'first',
          isNextButton: false,
          isStoryLink: false,
          src: 'scene_17_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '39.63%',
          width: '28.91%',
          xPos: '4.22%',
          yPos: '10.37%',
        },
        {
          classes: 'second animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_18_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '16.11%',
          width: '33.54%',
          xPos: '28.33%',
          yPos: '55.28%',
        },
      ],
      nextFrame: 19,
      prevFrame: 17,
      shouldTransition: false,
    },
    {
      //19.Scene 20
      backgroundSrc: 'scene_15.png',
      elements: [
        {
          classes: 'first',
          isNextButton: false,
          isStoryLink: false,
          src: 'fisherman.gif',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '55.28%',
          width: '44.01%',
          xPos: '51.56%',
          yPos: '4.54%',
        },
        {
          classes: 'second animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_19_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '16.02%',
          width: '33.54%',
          xPos: '37.76%',
          yPos: '1.76%',
        },
      ],
      nextFrame: 20,
      prevFrame: 18,
      shouldTransition: false,
    },
    {
      //20.Scene 21
      backgroundSrc: 'scene_15.png',
      elements: [
        {
          classes: 'first',
          isNextButton: false,
          isStoryLink: false,
          src: 'fisherman.gif',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '55.28%',
          width: '44.01%',
          xPos: '51.56%',
          yPos: '4.54%',
        },
        {
          classes: 'second animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_20_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '17.96%',
          width: '33.54%',
          xPos: '2.55%',
          yPos: '55.46%',
        },
      ],
      nextFrame: 10,
      prevFrame: 19,
      shouldTransition: true,
    },
    {
      //21.Scene 22
      backgroundSrc: 'scene_21.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_21_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '14.07%',
          width: '23.85%',
          xPos: '51.09%',
          yPos: '9.91%',
        },
      ],
      nextFrame: 22,
      prevFrame: 10,
      shouldTransition: false,
    },
    {
      //22.Scene 23
      backgroundSrc: 'scene_21.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_22_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '23.8%',
          width: '29.69%',
          xPos: '1.09%',
          yPos: '73.52%',
        },
      ],
      nextFrame: 23,
      prevFrame: 21,
      shouldTransition: false,
    },
    {
      //23.Scene 24
      backgroundSrc: 'scene_21.png',
      elements: [
        {
          classes: 'first',
          isNextButton: false,
          isStoryLink: false,
          src: 'scene_23_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '53.43%',
          width: '30.1%',
          xPos: '1.88%',
          yPos: '41.57%',
        },
        {
          classes: 'second animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_23_e2.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '28.52%',
          width: '34.95%',
          xPos: '22.71%',
          yPos: '28.8%',
        },
      ],
      nextFrame: 10,
      prevFrame: 22,
      shouldTransition: true,
    },
    {
      //24.Scene 25
      backgroundSrc: 'scene_24.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_24_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '16.85%',
          width: '28.59%',
          xPos: '48.65%',
          yPos: '1.3%',
        },
      ],
      nextFrame: 25,
      prevFrame: 10,
      shouldTransition: false,
    },
    {
      //25.Scene 26
      backgroundSrc: 'scene_24.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_25_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '13.89%',
          width: '22.03%',
          xPos: '11.35%',
          yPos: '9.07%',
        },
      ],
      nextFrame: 26,
      prevFrame: 24,
      shouldTransition: false,
    },
    {
      //26.Scene 27
      backgroundSrc: 'scene_24.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_26_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '17.22%',
          width: '25.89%',
          xPos: '11.25%',
          yPos: '6.02%',
        },
      ],
      nextFrame: 27,
      prevFrame: 25,
      shouldTransition: false,
    },
    {
      //27.Scene 28
      backgroundSrc: 'scene_24.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_27_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '23.06%',
          width: '28.7%',
          xPos: '29.69%',
          yPos: '28.33%',
        },
      ],
      nextFrame: 28,
      prevFrame: 26,
      shouldTransition: true,
    },
    {
      //28.Scene 29
      backgroundSrc: 'scene_28.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_28_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '20.46%',
          width: '34.79%',
          xPos: '52.97%',
          yPos: '16.3%',
        },
      ],
      nextFrame: 29,
      prevFrame: 27,
      shouldTransition: false,
    },
    {
      //29.Scene 30
      backgroundSrc: 'scene_28.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_29_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '19.17%',
          width: '30.63%',
          xPos: '54.01%',
          yPos: '24.81%',
        },
      ],
      nextFrame: 30,
      prevFrame: 28,
      shouldTransition: false,
    },
    {
      //30.Scene 31
      backgroundSrc: 'scene_28.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_30_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '27.31%',
          width: '34.06%',
          xPos: '12.86%',
          yPos: '18.7%',
        },
      ],
      nextFrame: 31,
      prevFrame: 29,
      shouldTransition: false,
    },
    {
      //31.Scene 32
      backgroundSrc: 'scene_28.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_31_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '35.0%',
          width: '39.64%',
          xPos: '34.95%',
          yPos: '13.61%',
        },
      ],
      nextFrame: 32,
      prevFrame: 30,
      shouldTransition: false,
    },
    {
      //32.Scene 33
      backgroundSrc: 'scene_28.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_32_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '30.0%',
          width: '34.95%',
          xPos: '10.94%',
          yPos: '15.83%',
        },
      ],
      nextFrame: 33,
      prevFrame: 31,
      shouldTransition: true,
    },
    {
      //33.Scene 34
      backgroundSrc: 'scene_33.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_33_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '17.96%',
          width: '32.66%',
          xPos: '2.24%',
          yPos: '41.02%',
        },
      ],
      nextFrame: 34,
      prevFrame: 32,
      shouldTransition: false,
    },
    {
      //34.Scene 35
      backgroundSrc: 'scene_33.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_34_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '15.0%',
          width: '31.41%',
          xPos: '2.24%',
          yPos: '42.5%',
        },
      ],
      nextFrame: 35,
      prevFrame: 33,
      shouldTransition: true,
      nextGameIs: 'match',
    },
    {
      //35.Scene 36
      backgroundSrc: 'scene_35.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_35_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '18.43%',
          width: '33.54%',
          xPos: '2.66%',
          yPos: '14.35%',
        },
      ],
      nextFrame: 36,
      prevFrame: 34,
      shouldTransition: false,
    },
    {
      //36.Scene 37
      backgroundSrc: 'scene_35.png',
      elements: [
        {
          classes: 'first animation fade-in',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_36_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '16.11%',
          width: '33.54%',
          xPos: '0.73%',
          yPos: '23.8%',
        },
      ],
      nextFrame: 37,
      prevFrame: 35,
      shouldTransition: true,
    },
    {
      //37.Scene 38
      backgroundSrc: 'start.png',
      elements: [
        {
          classes: 'first animation bottom-to-top',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_37_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '16.11%',
          width: '33.54%',
          xPos: '0.73%',
          yPos: '23.8%',
        },
      ],
      nextFrame: 38,
      prevFrame: 36,
      shouldTransition: false,
    },
    {
      //38.Scene 39
      backgroundSrc: 'start.png',
      elements: [
        {
          classes: 'first animation left-to-right',
          isNextButton: true,
          isStoryLink: false,
          src: 'scene_38_e1.png',
          storyLinkedFrame: -1,
          storyLinkViewed: false,
          styles: '',
          height: '17.59%',
          width: '34.32%',
          xPos: '8.18%',
          yPos: '76.67%',
        },
      ],
      nextFrame: 39,
      prevFrame: 37,
      shouldTransition: false,
    },
  ];

  constructor() {}

  getFrame(pos: number): StoryImage {
    return this.data[pos];
  }

  getLimit(): number {
    return this.data.length;
  }

  linkedStoryViewed(pos: number, fElemPos: number): void {
    this.data[pos].elements[fElemPos].storyLinkViewed = true;
  }
}
